[project]
requires-python = ">=3.11,<3.14"
name = "rnat-feedback-design"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "argparse>=1.4.0",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "scipy>=1.17.1",
]
[tool.uv.sources]
nupack = { path = "./vendor/nupack-4.0.2.0/package", editable = false }
